OLAssignment/Controllers/CourseController.cs
using OLAssignment.BizRepository;
using OLAssignment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace OLAssignment.Controllers
{
    public class CourseController : Controller
    {
        IBizRepository<Course, int> corRepo;
        IBizRepository<Trainer, int> trnRepo;
        IBizRepository<Student, int> sturepo;
        OLDbContext context;

        public CourseController()
        {
            sturepo = new StudentBizRepo();
            corRepo = new CourseBizRepo();
            context = new OLDbContext();
        }

        // GET: Course  
        
        public ActionResult Index()
        {
            var result = corRepo.GetData();
            var studentidtmp = sturepo.GetData();
            var studidtmp = studentidtmp.Where(s => s.Id == User.Identity.GetUserId()).FirstOrDefault().Id.ToString();
            ViewBag.Studid = studidtmp;
            return View(result);
        }

        public ActionResult SCourses(string query)
        {
            var result = corRepo.GetData();
            result = result.Where(e => e.CourseName == query).ToList();
            return View(result);
        }

        public ActionResult GetCourses(string uid)
        {
            var result = corRepo.GetData();
            result = result.Where(e => e.CTrainer.Id == uid).ToList();
            return View(result);
        }

        public ActionResult Details(int id)
        {
            TempData["CourseRowId"] = id;
            
            return RedirectToAction("Index", "Module");
        }

        public ActionResult AddCourse(string uid)
        {
            var tmp = context.Trainers.Where(e => e.Id == uid).FirstOrDefault();
            var result = new Course();
            result.CTrainer = tmp;
            //result.CTrainer = context.Trainers.Where(e => e.Id == uid).FirstOrDefault();
            //result.CTrainer = (Trainer)TempData["Trainer"];
            if (context.Courses.Count() > 0)
            {
                string cid = context.Courses.OrderByDescending(e => e.CourseId).First().CourseId;
                string[] temp = cid.Split(':');
                temp[1] = (Convert.ToInt32(temp[1]) + 1).ToString("00");
                cid = temp[0] + ':' + temp[1];
                result.CourseId = cid;
            }
            else
            {
                result.CourseId = "C:1";
            }

            return View(result);
        }

        [HttpPost]
        public ActionResult AddCourse(Course cor)
        {
            if (ModelState.IsValid)
            {
                corRepo.Create(cor);
                return RedirectToAction("Index", "Home");
            }
            return View(cor);
        }


        public ActionResult Create()
        {
            var result = new Course();
            return View(result);
        }

        [HttpPost]
        public ActionResult Create(Course cor)
        {
            if (ModelState.IsValid)
            {
                corRepo.Create(cor);
                return RedirectToAction("Index");
            }
            return View(cor);
        }

        public ActionResult Edit(int id)
        {
            var result = corRepo.GetData(id);
            return View(result);
        }

        [HttpPost]
        public ActionResult Edit(int id, Course cor)
        {
            if (ModelState.IsValid)
            {
                corRepo.Update(id, cor);
                return RedirectToAction("Index");
            }
            return View(cor);
        }

        public ActionResult Delete(int id)
        {
            var result = corRepo.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

OLAssignment/Controllers/StudentCourseController.cs
using OLAssignment.BizRepository;
using OLAssignment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OLAssignment.Controllers
{
    public class StudentCourseController : Controller
    {
        IBizRepository<StudentCourse, int> scRepo;
        OLDbContext context;

        public StudentCourseController()
        {
            scRepo = new StudentCourseRepo();
            context = new OLDbContext();
        }

        // GET: StudentCourse
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Student")]
        public ActionResult CourseEnroll(int corid,string stuid)
        {
            StudentCourse cs = new StudentCourse();
            cs.CourseId = context.Courses.Where(e => e.CourseRowId == corid).FirstOrDefault();
            cs.StudentId = context.Students.Where(e => e.Id == stuid).FirstOrDefault();
            cs.Status = 0;
            context.StudentCourses.Add(cs);
            context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult GetEnrolledCourse(string uid)
        {
            Student std = context.Students.Where(e => e.Id == uid).FirstOrDefault();

            List<StudentCourse> result = context.StudentCourses.Where(e => e.StudentId.StudentRowId == std.StudentRowId).ToList();
            return View(result);
        }


    }
}

OLAssignment/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Learing Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Online Platform", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>


                    @if (User.IsInRole("Student"))
                    {
                        //<li>@Html.ActionLink("Role", "Index", "Role")</li>
                        //<li>@Html.ActionLink("Courses", "Index", "Course")</li>
                        <li>@Html.ActionLink("Courses", "Index", "Course")</li>
                        <li>@Html.ActionLink("My Course", "GetEnrolledCourse", "StudentCourse", routeValues: new { uid = User.Identity.GetUserId() }, htmlAttributes: new { })</li>
                    }

                    @if (User.IsInRole("Trainer"))
                    {
                        //<li>@Html.ActionLink("Role", "Index", "Role")</li>
                        //<li>@Html.ActionLink("Trainer", "Index", "Trainer")</li>
                        <li>@Html.ActionLink("My Class", "GetCourses", "Course", routeValues: new { uid = User.Identity.GetUserId() }, htmlAttributes: new { })</li>
                        <li>@Html.ActionLink(linkText: "Add new Course", actionName: "AddCourse", controllerName: "Course", routeValues: new { uid = User.Identity.GetUserId() }, htmlAttributes: new { }  )</li>
                    }

                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Your Online Learning platform</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>